#!/bin/bash

appid='uni/app-office'
choice=nextCloud
env=vps

role()

appid='uni/app-office'
choice=libreOffice
env=native

role()

role(){
  cd $HOME
  ln -srf $appid/$choice/$env/ ~/.ansible/roles/$choice.$env
}
